/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HelpRouteImport } from './routes/help'
import { Route as MobileConsentRouteImport } from './routes/mobile-consent'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin/attendance'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminLocationRouteImport } from './routes/_authenticated/admin/location'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedUserAttendanceRouteImport } from './routes/_authenticated/user/attendance'
import { Route as AuthenticatedUserDashboardRouteImport } from './routes/_authenticated/user/dashboard'
import { Route as AuthenticatedUserDevicesRouteImport } from './routes/_authenticated/user/devices'
import { Route as AuthenticatedUserNotificationsRouteImport } from './routes/_authenticated/user/notifications'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users.$id'
import { Route as AuthenticatedUserSecurityIndexRouteImport } from './routes/_authenticated/user/security/index'
import { Route as AuthenticatedUserSecurityActivityRouteImport } from './routes/_authenticated/user/security/activity'
import { Route as AuthenticatedUserSecurityLocationRouteImport } from './routes/_authenticated/user/security/location'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileConsentRoute = MobileConsentRouteImport.update({
  id: '/mobile-consent',
  path: '/mobile-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/admin/attendance',
    path: '/admin/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/admin/events',
    path: '/admin/events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLocationRoute =
  AuthenticatedAdminLocationRouteImport.update({
    id: '/admin/location',
    path: '/admin/location',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserAttendanceRoute =
  AuthenticatedUserAttendanceRouteImport.update({
    id: '/user/attendance',
    path: '/user/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserDashboardRoute =
  AuthenticatedUserDashboardRouteImport.update({
    id: '/user/dashboard',
    path: '/user/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserDevicesRoute =
  AuthenticatedUserDevicesRouteImport.update({
    id: '/user/devices',
    path: '/user/devices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserNotificationsRoute =
  AuthenticatedUserNotificationsRouteImport.update({
    id: '/user/notifications',
    path: '/user/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedUserSecurityIndexRoute =
  AuthenticatedUserSecurityIndexRouteImport.update({
    id: '/user/security/',
    path: '/user/security/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserSecurityActivityRoute =
  AuthenticatedUserSecurityActivityRouteImport.update({
    id: '/user/security/activity',
    path: '/user/security/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserSecurityLocationRoute =
  AuthenticatedUserSecurityLocationRouteImport.update({
    id: '/user/security/location',
    path: '/user/security/location',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/mobile-consent': typeof MobileConsentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/location': typeof AuthenticatedAdminLocationRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/user/attendance': typeof AuthenticatedUserAttendanceRoute
  '/user/dashboard': typeof AuthenticatedUserDashboardRoute
  '/user/devices': typeof AuthenticatedUserDevicesRoute
  '/user/notifications': typeof AuthenticatedUserNotificationsRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/user/security/activity': typeof AuthenticatedUserSecurityActivityRoute
  '/user/security/location': typeof AuthenticatedUserSecurityLocationRoute
  '/user/security/': typeof AuthenticatedUserSecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/mobile-consent': typeof MobileConsentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/location': typeof AuthenticatedAdminLocationRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/user/attendance': typeof AuthenticatedUserAttendanceRoute
  '/user/dashboard': typeof AuthenticatedUserDashboardRoute
  '/user/devices': typeof AuthenticatedUserDevicesRoute
  '/user/notifications': typeof AuthenticatedUserNotificationsRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/user/security/activity': typeof AuthenticatedUserSecurityActivityRoute
  '/user/security/location': typeof AuthenticatedUserSecurityLocationRoute
  '/user/security': typeof AuthenticatedUserSecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/mobile-consent': typeof MobileConsentRoute
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/location': typeof AuthenticatedAdminLocationRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/user/attendance': typeof AuthenticatedUserAttendanceRoute
  '/_authenticated/user/dashboard': typeof AuthenticatedUserDashboardRoute
  '/_authenticated/user/devices': typeof AuthenticatedUserDevicesRoute
  '/_authenticated/user/notifications': typeof AuthenticatedUserNotificationsRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/user/security/activity': typeof AuthenticatedUserSecurityActivityRoute
  '/_authenticated/user/security/location': typeof AuthenticatedUserSecurityLocationRoute
  '/_authenticated/user/security/': typeof AuthenticatedUserSecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/help'
    | '/mobile-consent'
    | '/admin/login'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/location'
    | '/admin/reports'
    | '/admin/users'
    | '/user/attendance'
    | '/user/dashboard'
    | '/user/devices'
    | '/user/notifications'
    | '/admin/users/$id'
    | '/user/security/activity'
    | '/user/security/location'
    | '/user/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/help'
    | '/mobile-consent'
    | '/admin/login'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/location'
    | '/admin/reports'
    | '/admin/users'
    | '/user/attendance'
    | '/user/dashboard'
    | '/user/devices'
    | '/user/notifications'
    | '/admin/users/$id'
    | '/user/security/activity'
    | '/user/security/location'
    | '/user/security'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/help'
    | '/mobile-consent'
    | '/admin/login'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/location'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/users'
    | '/_authenticated/user/attendance'
    | '/_authenticated/user/dashboard'
    | '/_authenticated/user/devices'
    | '/_authenticated/user/notifications'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/user/security/activity'
    | '/_authenticated/user/security/location'
    | '/_authenticated/user/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  MobileConsentRoute: typeof MobileConsentRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-consent': {
      id: '/mobile-consent'
      path: '/mobile-consent'
      fullPath: '/mobile-consent'
      preLoaderRoute: typeof MobileConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/location': {
      id: '/_authenticated/admin/location'
      path: '/admin/location'
      fullPath: '/admin/location'
      preLoaderRoute: typeof AuthenticatedAdminLocationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/attendance': {
      id: '/_authenticated/user/attendance'
      path: '/user/attendance'
      fullPath: '/user/attendance'
      preLoaderRoute: typeof AuthenticatedUserAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/dashboard': {
      id: '/_authenticated/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof AuthenticatedUserDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/devices': {
      id: '/_authenticated/user/devices'
      path: '/user/devices'
      fullPath: '/user/devices'
      preLoaderRoute: typeof AuthenticatedUserDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/notifications': {
      id: '/_authenticated/user/notifications'
      path: '/user/notifications'
      fullPath: '/user/notifications'
      preLoaderRoute: typeof AuthenticatedUserNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/user/security/': {
      id: '/_authenticated/user/security/'
      path: '/user/security'
      fullPath: '/user/security/'
      preLoaderRoute: typeof AuthenticatedUserSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/security/activity': {
      id: '/_authenticated/user/security/activity'
      path: '/user/security/activity'
      fullPath: '/user/security/activity'
      preLoaderRoute: typeof AuthenticatedUserSecurityActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/security/location': {
      id: '/_authenticated/user/security/location'
      path: '/user/security/location'
      fullPath: '/user/security/location'
      preLoaderRoute: typeof AuthenticatedUserSecurityLocationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminLocationRoute: typeof AuthenticatedAdminLocationRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedUserAttendanceRoute: typeof AuthenticatedUserAttendanceRoute
  AuthenticatedUserDashboardRoute: typeof AuthenticatedUserDashboardRoute
  AuthenticatedUserDevicesRoute: typeof AuthenticatedUserDevicesRoute
  AuthenticatedUserNotificationsRoute: typeof AuthenticatedUserNotificationsRoute
  AuthenticatedUserSecurityActivityRoute: typeof AuthenticatedUserSecurityActivityRoute
  AuthenticatedUserSecurityLocationRoute: typeof AuthenticatedUserSecurityLocationRoute
  AuthenticatedUserSecurityIndexRoute: typeof AuthenticatedUserSecurityIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminLocationRoute: AuthenticatedAdminLocationRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedUserAttendanceRoute: AuthenticatedUserAttendanceRoute,
  AuthenticatedUserDashboardRoute: AuthenticatedUserDashboardRoute,
  AuthenticatedUserDevicesRoute: AuthenticatedUserDevicesRoute,
  AuthenticatedUserNotificationsRoute: AuthenticatedUserNotificationsRoute,
  AuthenticatedUserSecurityActivityRoute:
    AuthenticatedUserSecurityActivityRoute,
  AuthenticatedUserSecurityLocationRoute:
    AuthenticatedUserSecurityLocationRoute,
  AuthenticatedUserSecurityIndexRoute: AuthenticatedUserSecurityIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  MobileConsentRoute: MobileConsentRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
