// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // First attempt
    let { data } = await supabase.auth.getSession()
    let token = data.session?.access_token

    // If no token yet, the brokeredPreviewStorage may still be resolving the
    // postMessage handshake. Retry once after a short delay.
    if (!token) {
      await new Promise((r) => setTimeout(r, 400))
      const retry = await supabase.auth.getSession()
      token = retry.data.session?.access_token
    }

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
